---
- name: Dynamic Playbook V0.7
  hosts: localhost
  gather_facts: true

  vars:
    jsondata: "{{ lookup('file', 'payload.json') | from_json }}"
    technologies_to_install: "{{ jsondata.technologies }}"
    package_managers:
      - name: homebrew
        command: "/usr/local/bin/brew"
        install_command: "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: macports
        command: "/opt/local/bin/port"
        install_command: "curl -fsSL https://www.macports.org/install.sh | bash"

  tasks:
    - name: Gather Facts
      setup:
    
   # - name: Check operating system
   #   fail:
   #     msg: "This playbook is intended for macOS operating system only."
   #   when: ansible_facts['system'] != 'Darwin'

    #- name: Check architecture
     # fail:
      #  msg: "This playbook is intended for non-M1 ARM architecture."
     # when: ansible_facts['processor'] == 'aarch64'

    - name: Ping the hosts
      ping:

    - name: Print variable
      debug:
        var: jsondata

    - name: Print technologies
      debug:
        var: item
      loop: "{{ technologies_to_install }}"

    - name: Determine package manager
      set_fact:
        package_manager: "{{ ansible_facts.pkg_mgr }}"
      when: ansible_facts.pkg_mgr is defined
    
    - name: Debug package manager
      debug:
        var: package_manager

    - name: Install package managers if ansible_facts['pkg_mgr'] does not exist
      block:
        - name: Debug package manager
          debug:
            var: package_manager

        - name: Install package manager
          become: yes
          raw: "{{ package_manager.install_command }}"
          register: install_output
          retries: 3
          delay: 5
          failed_when: install_output is failed

        - name: Fail if package manager installation failed
          fail:
            msg: "Failed to install the package manager ({{ package_manager.name }})."
          when: install_output is failed

        - name: Verify package manager presence
          stat:
            path: "{{ package_manager.command }}"
          register: package_manager_verification

        - name: Debug package manager verification
          debug:
            var: package_manager

        - name: Fail if package manager not found
          fail:
            msg: "Package manager ({{ package_manager.name }}) not found on the system."
          when: not package_manager_verification.skipped

        - name: Set default package manager
          set_fact:
            ansible_facts:
              pkg_mgr: "{{ package_manager }}"

      when: package_manager is undefined

    - name: Install technologies with Homebrew
      become: yes
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ technologies_to_install }}"
      when: package_manager == 'homebrew'

    - name: Install technologies with MacPorts
      become: yes
      macports:
        name: "{{ item }}"
        state: present
      loop: "{{ technologies_to_install }}"
      when: package_manager == 'macports'

    - name: Print installation summary
      debug:
        msg: |
          Technology installations summary:
          Successfully installed: {{ technologies_to_install | difference(install_output.results) }}
          Failed installations: {{ install_output.results | rejectattr('rc', 'eq', 0) | map(attribute='item') | list }}
